# Generated by Django 5.2.1 on 2025-05-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppExamen', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='todo_list_id',
        ),
        migrations.AddField(
            model_name='task',
            name='todo_list',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='AppExamen.todolist'),
        ),
        migrations.AlterField(
            model_name='task',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
