# Generated by Django 5.2 on 2025-04-22 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AppResolution', '0002_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(blank=True, max_length=150, null=True, unique=True),
        ),
    ]
